server:
  port: 8080



spring:
  datasource:
    name: localhost
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis.demo.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      example:
        mapper : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSq


token: d0f4eaa10e1e4cbcaa907d62ecd512f1
appId: wxe8efa57e42e9b249
appSecret: 753feef9bd036cc52f96f0fdfa730416

wx:
  appId: wxe8efa57e42e9b249
  secret: 753feef9bd036cc52f96f0fdfa730416
  token: d0f4eaa10e1e4cbcaa907d62ecd512f1
  aesKey: KtOjqYWssGHc3A9GrkCD397b8gGk3Vrw8FcCqiSjfqa