server:
  port: 8080



spring:
  datasource:
    name: localhost
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis.demo.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      example:
        mapper : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSq


token: d0f4eaa10e1e4cbcaa907d62ecd512f1
appId: wxe8efa57e42e9b249
appSecret: 753feef9bd036cc52f96f0fdfa730416

wx:
  appId: wxe8efa57e42e9b249
  secret: 753feef9bd036cc52f96f0fdfa730416
  token: d0f4eaa10e1e4cbcaa907d62ecd512f1
  aesKey: KtOjqYWssGHc3A9GrkCD397b8gGk3Vrw8FcCqiSjfqa

alipay:
  appId: 9021000122682852
  sellerId: 2088721003898279
  privateKey: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCHd0B0Z9I7jXbHw4saG179bxfFOOYMIx/Vkq5UOzat0EHyyJkTXRFNu656iWjE8/D8517F/EvZbe1zPC9Xkra6f9sX5AFgdstEI6CQxsXoWGyoIE0FkQ45Fq93flCp6E98KNCk02vx73X8MQN+oclPexN4gm3NyetIEjnV6jHjGECnNEQmxfyKubFnxRDd0YxO/AbqErizKeiR47uTeQt2FuTC2fY5GHYuK7i0SceBPHmI6dzBnG1ytRaeAL5XmaSJFvCoV8eVy96vPVOsNaI3YXuceYXlH/5KbZ4UOo/vsbqRH3ppOEjToaijpoHwYwLvRafWA20Mgtyev/EiRVHrAgMBAAECggEAPm6bagqfPYsI/zAD39hVgv+8OMzsWROnDEs5xOA1Zw3gFwCUa/QskWK6GwdRHdQ/cI9BgoWwf1jGYqGOQBIB3Ron427Vo5ucOp8g1RiHBXobObEJTlN39p+Z5rx0eJn0aAh3gD9gNHRkMAJ21dnCabsTUirqaDlzEhg0R35T15EagcV+CmI+NuqNvLrbJU08Yz306d+9TO4eY8xeFkvJ6JDfRT6zbfNNqEN4nuLtejPDzrS9NNpjD5BBSNsS3YV8lJOACoeNddjATYEItPUsYrwM+YBkjDjZHmaaRP6AxuLVO7GrnZusamrrsGhTMcosKc7mOAFWrnmR6pv90d4iQQKBgQDlFjlQ6HvAzZNlO02tl94VwSkc9rRz1ngdnsnzsDQFMdKMMuFnEUsDCvfQeFiOShHakT6w2zQ1MMwjx4gpQHYEtpoRtiFl5BWh2RsA3jtbKnZx7WZJWUVwhbSRmQgC/KIOGCgu9vig1psHHhr7pDXOZyqtLXzklmGf0wyvn4SWuQKBgQCXYWF5S8fn69xzpILZFYjbv/I9HZsHoMJggzK3oDGqDE3FtiD3Mpgoa19LlVBaBhk+5l+jBV0iX6YEbIWRy/lDC/PL8YEAcvkTY1yeFfijib6X/qInQAkF7SMoqGrQcCp0twR0cN1a14BKS6OQp2W9DvHa1TaRRxrCPE8jJukbwwKBgBqNVN9X0uAp86eMFBjGvWrwFH/S6F90wD9OpEGmbqEbgTfWveFgU71qjAaRrFHxq9gVdZqyDX8MxNxwyAtf+U3ajEj5Py28HfXAYCzdlSuf5FKYHX7q5e2A0cj+X7tY5L+VdTLcVTzvItDUYHRCOCpQMtYXq54i//WyVIoWhxuhAoGAQraF0IDXHpxRUR2FFMpqv/19cfWkJt5wCzyGk2ojuP8nHyS+rnI7oESBgLvS53mckp3QM/XfL5Dbh0OUMcakmSmhTZWm9l206xh07q5cHyZLOozbRVTxJQ122yotuKJV843chrxesPQb86IV+V/sdD8r0vb3z1p4rnUJo0I4pSUCgYAjz602D6pLyczLKL7fMxXGJjr81kDMj27dKgpFqz7ICEo2ruT9PbnhnR0qg6nd4LeJOI2XNDFyuZ9/TcYyaQisLous3ewpdgYUzXkgO8uE8xXMqxSbyuTibrTJ9G26xQej/T+VNrgr3NhzaPXrRE40l6BcQQk8SJndf9QuD/N8EA=="
  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiMjkobYxS7BD4cVtDlmDzjKkT4AD95/BPI2+pdoTCnwUMMrQPryU4CLZ33C6Ic0o1ZED6Ebu4Ww8M0lYw1EcneP5h2wFxRj7GNCvDrIXpyTH+GZTG6EUPI4tAlZrH8dN8hVNwoXJ35ND2rgSqJDxqXAmlPJTQlj4I/V+A4WeKaND4DQuohZsIYaduPznvD6JYg4dA/qI25peXra8unbtzHNxrB+nwjgZB8ek31FzS9TiVavNHnOH/tDxr/rU229uraVzLqDO5cV6JqFL03J19FW/2J2Kb2X6hDvCurlupTd3gkciiSNBnzK128h5mtEHO4ZEE4phqOc8J8EWt/FeYQIDAQAB"
  notifyUrl: "https://5n7598547p.zicp.fun/pay/notify"
  returnUrl: ""
  gateWayUrl: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"