server:
  port: 8888



spring:
  datasource:
    name: localhost
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis.demo.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      example:
        mapper : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSq